# Generated by Django 4.0.2 on 2022-09-03 01:52

from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_1', models.CharField(max_length=1024, verbose_name='Image 1')),
                ('img_2', models.CharField(max_length=1024, verbose_name='Image 2')),
                ('title', models.CharField(max_length=1024, verbose_name='Title')),
                ('content', models.CharField(max_length=1024, verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, verbose_name='Name')),
                ('img', models.CharField(blank=True, max_length=1024, verbose_name='Image')),
                ('link', models.CharField(blank=True, max_length=1024, verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('infor', models.CharField(blank=True, max_length=1024, verbose_name='Information')),
                ('img', models.CharField(blank=True, max_length=1024, verbose_name='Image')),
                ('feedback', models.CharField(blank=True, max_length=1024, verbose_name='Feedback')),
                ('time', models.CharField(blank=True, max_length=1024, verbose_name='Time')),
            ],
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_link', models.CharField(max_length=1024, verbose_name='Background Link')),
            ],
        ),
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', martor.models.MartorField(verbose_name='description')),
                ('priority', models.IntegerField(default=0, verbose_name='priority')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=1024, verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='Narbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=1024, verbose_name='Name')),
                ('id_section', models.CharField(max_length=1024, verbose_name='ID')),
                ('link', models.CharField(max_length=1024, verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Title')),
                ('content', models.CharField(max_length=1024, verbose_name='Content')),
                ('bg', models.CharField(blank=True, max_length=1024, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_color', models.CharField(blank=True, max_length=1024, verbose_name='Theme Color')),
                ('text_color', models.CharField(blank=True, max_length=1024, verbose_name='Text Color')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='students', verbose_name='Image')),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('content', models.TextField(blank=True, max_length=1024, verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='teachers', verbose_name='Image')),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('content', models.TextField(blank=True, max_length=1024, verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, verbose_name='Name')),
                ('student', models.CharField(blank=True, max_length=1024, verbose_name='Student')),
                ('teacher', models.CharField(blank=True, max_length=1024, verbose_name='Teacher')),
                ('time', models.CharField(blank=True, max_length=1024, verbose_name='Time')),
                ('room_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addition', to='home.class')),
            ],
        ),
    ]
