# Generated by Django 4.0.6 on 2022-07-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('content', models.CharField(blank=True, max_length=255, verbose_name='content')),
                ('img_link', models.CharField(blank=True, max_length=255, verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255, verbose_name='number')),
                ('content', models.CharField(blank=True, max_length=255, verbose_name='content')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='Emath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='tile')),
                ('content', models.CharField(blank=True, max_length=255, verbose_name='content')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='link')),
                ('appstore', models.CharField(blank=True, max_length=255, verbose_name='appstore_link')),
                ('chplay', models.CharField(blank=True, max_length=255, verbose_name='chplay_link')),
            ],
        ),
        migrations.CreateModel(
            name='HomeButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.CharField(blank=True, max_length=255, verbose_name='name button')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='content1')),
                ('title2', models.CharField(blank=True, max_length=255, verbose_name='content2')),
                ('title3', models.CharField(blank=True, max_length=255, verbose_name='content3')),
                ('title4', models.CharField(blank=True, max_length=255, verbose_name='content4')),
                ('title5', models.CharField(blank=True, max_length=255, verbose_name='content5')),
            ],
        ),
        migrations.CreateModel(
            name='HomeImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='link img')),
                ('img_1', models.CharField(blank=True, max_length=255, verbose_name='img1')),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('link', models.CharField(max_length=255, verbose_name='link')),
            ],
        ),
    ]