# Generated by Django 4.0.6 on 2022-08-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecontent',
            name='title4',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='title5',
        ),
        migrations.AddField(
            model_name='homecontent',
            name='img',
            field=models.CharField(blank=True, max_length=1024, verbose_name='link image'),
        ),
    ]
