# Generated by Django 4.0.6 on 2022-08-04 02:26

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_achievement_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoppyRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='tile')),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=1024, verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='tile')),
                ('content', models.CharField(blank=True, max_length=255, verbose_name='content')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('link_img', models.CharField(blank=True, max_length=255, verbose_name='link image')),
                ('button', models.CharField(blank=True, max_length=255, verbose_name='button')),
                ('button_link', models.CharField(blank=True, max_length=255, verbose_name='link button')),
            ],
        ),
        migrations.DeleteModel(
            name='Emath',
        ),
        migrations.DeleteModel(
            name='HomeImg',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='title4',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='title5',
        ),
        migrations.AddField(
            model_name='homecontent',
            name='detail_1',
            field=models.CharField(blank=True, max_length=1024, verbose_name='detail 1'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='detail_2',
            field=models.CharField(blank=True, max_length=1024, verbose_name='detail 2'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='detail_3',
            field=models.CharField(blank=True, max_length=1024, verbose_name='detail 3'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='img',
            field=models.CharField(blank=True, max_length=1024, verbose_name='link image'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='path_1',
            field=models.CharField(blank=True, max_length=1024, verbose_name='path 1'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='path_2',
            field=models.CharField(blank=True, max_length=1024, verbose_name='path 2'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='path_3',
            field=models.CharField(blank=True, max_length=1024, verbose_name='path 3'),
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=martor.models.MartorField(blank=True, max_length=255, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='about',
            name='img_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='link img'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='content',
            field=martor.models.MartorField(blank=True, max_length=255, verbose_name='content'),
        ),
    ]