# Generated by Django 4.0.6 on 2022-08-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_coppyright_logo_new_delete_emath_delete_homeimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_button',
            field=models.CharField(blank=True, max_length=255, verbose_name='button'),
        ),
        migrations.AddField(
            model_name='about',
            name='button_link',
            field=models.CharField(blank=True, max_length=1024, verbose_name='button link'),
        ),
    ]
