# Generated by Django 4.0.6 on 2022-08-04 03:29

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_coppyright_logo_new_delete_emath_delete_homeimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=martor.models.MartorField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='content',
            field=martor.models.MartorField(blank=True, verbose_name='content'),
        ),
    ]
