# Generated by Django 4.0.6 on 2022-08-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_homeimg_homecontent_path_1_homecontent_path_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='detail_1',
            field=models.CharField(blank=True, max_length=1024, verbose_name='detail 1'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='detail_2',
            field=models.CharField(blank=True, max_length=1024, verbose_name='detail 2'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='detail_3',
            field=models.CharField(blank=True, max_length=1024, verbose_name='detail 3'),
        ),
    ]
