# Generated by Django 4.0.6 on 2022-08-04 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_about_about_button_about_button_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about_button',
            new_name='button',
        ),
    ]
