# Generated by Django 4.0.6 on 2022-08-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homecontent_detail_1_homecontent_detail_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='tile')),
                ('content', models.CharField(blank=True, max_length=255, verbose_name='content')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('link_img', models.CharField(blank=True, max_length=255, verbose_name='link image')),
                ('button', models.CharField(blank=True, max_length=255, verbose_name='link button')),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='img_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='link img'),
        ),
    ]
