# Generated by Django 4.0.6 on 2022-08-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_new_alter_about_img_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='button_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='link button'),
        ),
        migrations.AlterField(
            model_name='new',
            name='button',
            field=models.CharField(blank=True, max_length=255, verbose_name='button'),
        ),
    ]
