# Generated by Django 4.0.6 on 2022-08-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_class_name_remove_class_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
