# Generated by Django 4.0.6 on 2022-08-04 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_coppyright'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emath',
        ),
    ]
