# Generated by Django 4.0.2 on 2022-09-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_teacher_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='content',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Content'),
        ),
    ]
