# Generated by Django 4.0.2 on 2022-08-11 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_setting_remove_coppyright_text_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
