# Generated by Django 4.0.6 on 2022-09-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='content',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(upload_to='students', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='img',
            field=models.ImageField(upload_to='teachers', verbose_name='Image'),
        ),
    ]
