# Generated by Django 4.0.2 on 2022-08-11 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_setting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoppyRight',
        ),
    ]
