# Generated by Django 4.0.2 on 2022-08-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_coppyright'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoppyRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='tile')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_color', models.CharField(blank=True, max_length=255, verbose_name='Theme Color')),
                ('title_color', models.CharField(blank=True, max_length=255, verbose_name='Title Color')),
                ('text_color', models.CharField(blank=True, max_length=255, verbose_name='Text Color')),
            ],
        ),
    ]
