# Generated by Django 4.0.7 on 2022-10-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_contact_img_alter_feedback_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='img_1',
            field=models.ImageField(upload_to='about', verbose_name='image1'),
        ),
        migrations.AlterField(
            model_name='about',
            name='img_2',
            field=models.ImageField(upload_to='about', verbose_name='image2'),
        ),
    ]
