# Generated by Django 4.0.2 on 2022-08-11 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_coppyright_setting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='CoppyRight',
        ),
        migrations.DeleteModel(
            name='HomeButton',
        ),
        migrations.DeleteModel(
            name='HomeContent',
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
        migrations.DeleteModel(
            name='Navigation',
        ),
        migrations.DeleteModel(
            name='New',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
