# Generated by Django 4.0.7 on 2022-10-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_about_img_1_alter_about_img_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='bg',
            field=models.ImageField(upload_to='reason', verbose_name='background'),
        ),
    ]
