# Generated by Django 4.0.2 on 2022-08-13 02:25

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_delete_about_delete_achievement_delete_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('content', martor.models.MartorField(blank=True, max_length=255, verbose_name='content')),
                ('img_link', models.CharField(blank=True, max_length=255, verbose_name='link img')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255, verbose_name='number')),
                ('content', martor.models.MartorField(blank=True, max_length=255, verbose_name='content')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='CoppyRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='tile')),
            ],
        ),
        migrations.CreateModel(
            name='HomeButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.CharField(blank=True, max_length=255, verbose_name='name button')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='content1')),
                ('title2', models.CharField(blank=True, max_length=255, verbose_name='content2')),
                ('title3', models.CharField(blank=True, max_length=255, verbose_name='content3')),
                ('img', models.CharField(blank=True, max_length=1024, verbose_name='link image')),
                ('path_1', models.CharField(blank=True, max_length=1024, verbose_name='path 1')),
                ('detail_1', models.CharField(blank=True, max_length=1024, verbose_name='detail 1')),
                ('path_2', models.CharField(blank=True, max_length=1024, verbose_name='path 2')),
                ('detail_2', models.CharField(blank=True, max_length=1024, verbose_name='detail 2')),
                ('path_3', models.CharField(blank=True, max_length=1024, verbose_name='path 3')),
                ('detail_3', models.CharField(blank=True, max_length=1024, verbose_name='detail 3')),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=1024, verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('link', models.CharField(max_length=255, verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='tile')),
                ('content', models.CharField(blank=True, max_length=255, verbose_name='content')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('link_img', models.CharField(blank=True, max_length=255, verbose_name='link image')),
                ('button', models.CharField(blank=True, max_length=255, verbose_name='button')),
                ('button_link', models.CharField(blank=True, max_length=255, verbose_name='link button')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_color', models.CharField(blank=True, max_length=255, verbose_name='Theme Color')),
                ('title_color', models.CharField(blank=True, max_length=255, verbose_name='Title Color')),
                ('text_color', models.CharField(blank=True, max_length=255, verbose_name='Text Color')),
            ],
        ),
    ]
