# Generated by Django 4.0.2 on 2022-08-13 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_about_achievement_class_classroom_coppyright_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='CoppyRight',
        ),
        migrations.DeleteModel(
            name='HomeButton',
        ),
        migrations.DeleteModel(
            name='HomeContent',
        ),
        migrations.DeleteModel(
            name='Navigation',
        ),
        migrations.DeleteModel(
            name='New',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
