# Generated by Django 4.0.2 on 2022-08-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_delete_about_delete_achievement_delete_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_color', models.CharField(max_length=1024, verbose_name='Theme Color')),
                ('text_color', models.CharField(max_length=1024, verbose_name='Text Color')),
            ],
        ),
    ]
