# Generated by Django 4.0.2 on 2022-08-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=1024, verbose_name='Name')),
                ('id_section', models.CharField(max_length=1024, verbose_name='ID')),
                ('link', models.CharField(max_length=1024, verbose_name='link')),
            ],
        ),
    ]
