# Generated by Django 4.0.2 on 2022-08-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_narbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_link', models.CharField(max_length=1024, verbose_name='Background Link')),
            ],
        ),
    ]
