# Generated by Django 4.0.2 on 2022-08-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_homebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_1', models.CharField(max_length=1024, verbose_name='Image 1')),
                ('img_2', models.CharField(max_length=1024, verbose_name='Image 2')),
                ('title', models.CharField(max_length=1024, verbose_name='Title')),
                ('content', models.CharField(max_length=1024, verbose_name='Content')),
            ],
        ),
    ]
