# Generated by Django 4.0.2 on 2022-08-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=1024, verbose_name='Image')),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('content', models.CharField(blank=True, max_length=1024, verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=1024, verbose_name='Image')),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('content', models.CharField(blank=True, max_length=1024, verbose_name='Content')),
            ],
        ),
        migrations.AlterField(
            model_name='reason',
            name='bg',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Image'),
        ),
    ]
