# Generated by Django 4.0.2 on 2022-08-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_student_teacher_alter_reason_bg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('student', models.CharField(blank=True, max_length=1024, verbose_name='Student')),
                ('teacher', models.CharField(blank=True, max_length=1024, verbose_name='Teacher')),
                ('time', models.CharField(blank=True, max_length=1024, verbose_name='Time')),
            ],
        ),
    ]
