# Generated by Django 4.0.2 on 2022-08-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='img',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Image'),
        ),
    ]
