# Generated by Django 4.0.2 on 2022-08-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_feedback_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='content',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Content'),
        ),
    ]
