# Generated by Django 4.0.2 on 2022-08-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_teacher_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class02',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('student', models.CharField(blank=True, max_length=1024, verbose_name='Student')),
                ('teacher', models.CharField(blank=True, max_length=1024, verbose_name='Teacher')),
                ('time', models.CharField(blank=True, max_length=1024, verbose_name='Time')),
            ],
        ),
        migrations.CreateModel(
            name='Class03',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('student', models.CharField(blank=True, max_length=1024, verbose_name='Student')),
                ('teacher', models.CharField(blank=True, max_length=1024, verbose_name='Teacher')),
                ('time', models.CharField(blank=True, max_length=1024, verbose_name='Time')),
            ],
        ),
        migrations.RenameModel(
            old_name='Class',
            new_name='Class01',
        ),
    ]
