# Generated by Django 4.0.2 on 2022-08-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_class02_class03_rename_class_class01'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='text_color',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Text Color'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='theme_color',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Theme Color'),
        ),
    ]
