# Generated by Django 4.0.2 on 2022-08-17 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_choice_question_delete_class_delete_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
