# Generated by Django 4.0.2 on 2022-08-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_question_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
