# Generated by Django 4.0.2 on 2022-08-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_choice_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='name',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Name'),
        ),
    ]
