# Generated by Django 4.0.2 on 2022-08-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_class_room_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='votes',
        ),
        migrations.AddField(
            model_name='room',
            name='student',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='room',
            name='teacher',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Teacher'),
        ),
        migrations.AddField(
            model_name='room',
            name='time',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Time'),
        ),
    ]
