# Generated by Django 4.0.2 on 2022-08-17 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_remove_room_votes_room_student_room_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room',
            new_name='room_parent',
        ),
    ]
