# Generated by Django 4.0.2 on 2022-08-22 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_rename_room_room_room_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class01',
        ),
        migrations.DeleteModel(
            name='Class02',
        ),
        migrations.DeleteModel(
            name='Class03',
        ),
    ]
