# Generated by Django 4.0.2 on 2022-08-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_delete_class01_delete_class02_delete_class03'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, verbose_name='Name')),
                ('img', models.ImageField(blank=True, max_length=1024, upload_to='', verbose_name='Image')),
                ('link', models.CharField(blank=True, max_length=1024, verbose_name='Link')),
            ],
        ),
    ]
