# Generated by Django 4.0.2 on 2022-08-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='img',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Image'),
        ),
    ]
